CREATE TABLE "users" (
  "id" uuid PRIMARY KEY,
  "email" varchar UNIQUE,
  "phone" varchar UNIQUE,
  "password_hash" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "login_tokens" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid,
  "code" varchar(6),
  "expires_at" timestamp,
  "used" boolean,
  "created_at" timestamp
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE,
  "description" text
);

CREATE TABLE "permissions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE,
  "description" text
);

CREATE TABLE "role_permissions" (
  "role_id" integer,
  "permission_id" integer,
  PRIMARY KEY ("role_id", "permission_id")
);

CREATE TABLE "user_roles" (
  "user_id" uuid,
  "role_id" integer,
  PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE "patients" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid,
  "first_name" varchar,
  "last_name" varchar,
  "document_type" varchar,
  "document_number" varchar,
  "birth_date" date,
  "gender" varchar,
  "address" text,
  "emergency_contact" jsonb,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "doctors" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid,
  "first_name" varchar,
  "last_name" varchar,
  "specialty_id" integer,
  "active" boolean,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "specialties" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE,
  "description" text
);

CREATE TABLE "nurses" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid,
  "first_name" varchar,
  "last_name" varchar,
  "active" boolean
);

CREATE TABLE "rooms" (
  "id" uuid PRIMARY KEY,
  "name" text,
  "location" text,
  "capacity" integer
);

CREATE TABLE "departments" (
  "id" uuid PRIMARY KEY,
  "name" text UNIQUE,
  "description" text
);

CREATE TABLE "slots" (
  "id" uuid PRIMARY KEY,
  "doctor_id" uuid,
  "room_id" uuid,
  "start_ts" timestamp,
  "end_ts" timestamp,
  "duration_minutes" integer,
  "status" varchar
);

CREATE TABLE "appointments" (
  "id" uuid PRIMARY KEY,
  "patient_id" uuid,
  "slot_id" uuid UNIQUE,
  "status" varchar,
  "reason" text,
  "created_by" uuid,
  "created_at" timestamp
);

CREATE TABLE "appointment_notes" (
  "id" uuid PRIMARY KEY,
  "appointment_id" uuid,
  "doctor_id" uuid,
  "notes" text,
  "prescriptions" jsonb,
  "created_at" timestamp
);

CREATE TABLE "tickets" (
  "id" uuid PRIMARY KEY,
  "patient_id" uuid,
  "origin" varchar,
  "status" varchar,
  "created_at" timestamp
);

CREATE TABLE "triage_records" (
  "id" uuid PRIMARY KEY,
  "ticket_id" uuid,
  "level" varchar,
  "vitals" jsonb,
  "notes" text,
  "created_by" uuid,
  "created_at" timestamp
);

CREATE TABLE "notifications" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid,
  "channel" varchar,
  "content" text,
  "status" varchar,
  "created_at" timestamp
);

CREATE TABLE "conversation" (
  "id" uuid PRIMARY KEY,
  "sender_id" uuid,
  "receiver_id" uuid,
  "channel" varchar,
  "created_at" timestamp
);

CREATE TABLE "messages" (
  "id" uuid PRIMARY KEY,
  "conversationId" uuid,
  "sender_id" uuid,
  "receiver_id" uuid,
  "content" text,
  "created_at" timestamp
);

CREATE TABLE "audit_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid,
  "action" text,
  "entity" text,
  "entity_id" uuid,
  "payload" jsonb,
  "created_at" timestamp
);

CREATE INDEX ON "users" ("created_at");

CREATE INDEX ON "login_tokens" ("user_id");

CREATE INDEX ON "login_tokens" ("code");

CREATE INDEX ON "login_tokens" ("expires_at");

CREATE INDEX ON "role_permissions" ("role_id");

CREATE INDEX ON "role_permissions" ("permission_id");

CREATE INDEX ON "user_roles" ("user_id");

CREATE INDEX ON "user_roles" ("role_id");

CREATE INDEX ON "patients" ("user_id");

CREATE INDEX ON "patients" ("document_number");

CREATE INDEX ON "patients" ("last_name", "first_name");

CREATE INDEX ON "doctors" ("user_id");

CREATE INDEX ON "doctors" ("specialty_id");

CREATE INDEX ON "doctors" ("active");

CREATE INDEX ON "nurses" ("user_id");

CREATE INDEX ON "nurses" ("active");

CREATE INDEX ON "rooms" ("name");

CREATE UNIQUE INDEX ON "slots" ("doctor_id", "start_ts");

CREATE INDEX ON "slots" ("room_id");

CREATE INDEX ON "slots" ("status", "start_ts");

CREATE INDEX ON "appointments" ("patient_id");

CREATE INDEX ON "appointments" ("created_by");

CREATE INDEX ON "appointments" ("status");

CREATE INDEX ON "appointments" ("created_at");

CREATE INDEX ON "appointment_notes" ("appointment_id");

CREATE INDEX ON "appointment_notes" ("doctor_id");

CREATE INDEX ON "tickets" ("patient_id");

CREATE INDEX ON "tickets" ("status");

CREATE INDEX ON "tickets" ("created_at");

CREATE INDEX ON "triage_records" ("ticket_id");

CREATE INDEX ON "triage_records" ("created_by");

CREATE INDEX ON "triage_records" ("created_at");

CREATE INDEX ON "notifications" ("user_id");

CREATE INDEX ON "notifications" ("status");

CREATE INDEX ON "notifications" ("created_at");

CREATE INDEX ON "conversation" ("sender_id", "receiver_id");

CREATE INDEX ON "conversation" ("channel");

CREATE INDEX ON "messages" ("conversationId");

CREATE INDEX ON "messages" ("created_at");

CREATE INDEX ON "messages" ("sender_id", "created_at");

CREATE INDEX ON "audit_logs" ("user_id");

CREATE INDEX ON "audit_logs" ("entity", "entity_id");

CREATE INDEX ON "audit_logs" ("created_at");

ALTER TABLE "login_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "patients" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "doctors" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "doctors" ADD FOREIGN KEY ("specialty_id") REFERENCES "specialties" ("id");

ALTER TABLE "nurses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "slots" ADD FOREIGN KEY ("doctor_id") REFERENCES "doctors" ("id");

ALTER TABLE "slots" ADD FOREIGN KEY ("room_id") REFERENCES "rooms" ("id");

ALTER TABLE "appointments" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id");

ALTER TABLE "appointments" ADD FOREIGN KEY ("slot_id") REFERENCES "slots" ("id");

ALTER TABLE "appointments" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "appointment_notes" ADD FOREIGN KEY ("appointment_id") REFERENCES "appointments" ("id");

ALTER TABLE "appointment_notes" ADD FOREIGN KEY ("doctor_id") REFERENCES "doctors" ("id");

ALTER TABLE "tickets" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id");

ALTER TABLE "triage_records" ADD FOREIGN KEY ("ticket_id") REFERENCES "tickets" ("id");

ALTER TABLE "triage_records" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "conversation" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id");

ALTER TABLE "conversation" ADD FOREIGN KEY ("receiver_id") REFERENCES "users" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("conversationId") REFERENCES "conversation" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("receiver_id") REFERENCES "users" ("id");

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
